### ISSUE TITLE
Gruppe Adler Button im Hauptmenü muss geupdatet werden

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/gruppe_adler_mod#102]
Verweist auf falschen Server!

**Comment by DerZade** [comment]
Are you sure about that?

Looks like we are using the URL and not the IP.
https://github.com/gruppe-adler/gruppe_adler_mod/blob/master/addons/ui/functions/directConnect/fn_connectToServer.sqf#L23
