### ISSUE TITLE
zeus, monitoring: Shows LR Frequenzies on players without LR and does not show SR Frequenzies

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/gruppe_adler_mod#118]
Pic: https://imgur.com/a/rhwS64J

**Comment by dedmen** [comment]
Also I think it should be MHz

**Comment by McDiod** [comment]
>Also I think it should be MHz

Between this and the function returning the local player's frequencies over and over again, I'm wondering if I wrote this at 3 in the morning 🤔
