### ISSUE TITLE
bug in zeus addon

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/gruppe_adler_mod#129]
happens when ending the mission and returning to lobby (and possibly other places)

20:05:28 Error in expression <SW", -1]) isEqualTo -1) && {!((_loadout select 9 select 2) isEqualTo "")}) then >
20:05:28   Error position: <select 9 select 2) isEqualTo "")}) then >
20:05:28   Error Zero divisor
20:05:28 File x\GRAD\addons\zeus\XEH_preClientInit.sqf, line 106
20:05:28 Error in expression <LR", -1]) isEqualTo -1) && {!((_loadout select 5 select 0) isEqualTo "")}) then >
20:05:28   Error position: <select 5 select 0) isEqualTo "")}) then >
20:05:28   Error Zero divisor
20:05:28 File x\GRAD\addons\zeus\XEH_preClientInit.sqf, line 117

**Comment by AdlerSalbei** [comment]
Weird, getUnitLoadout sollte immer mindestens ein "" zurück geben.

**Comment by nomisum** [comment]
Happens also in 3DEN. My guess is one of the arrays accessed with select is too short in certain circumstances.

**Comment by AdlerSalbei** [comment]
It happens becous the getUnitLoadouut array sometimes is []

**Comment by AdlerSalbei** [comment]
fixed

**Comment by nomisum** [comment]
```
 1:05:01 Error in expression <SW", -1]) isEqualTo -1) && {!((_loadout select 9 select 2) isEqualTo "")}) then >
 1:05:01   Error position: <select 9 select 2) isEqualTo "")}) then >
 1:05:01   Error Zero divisor
 1:05:01 File x\GRAD\addons\zeus\XEH_preClientInit.sqf, line 106
 1:05:01 Error in expression <LR", -1]) isEqualTo -1) && {!((_loadout select 5 select 0) isEqualTo "")}) then >
 1:05:01   Error position: <select 5 select 0) isEqualTo "")}) then >
 1:05:01   Error Zero divisor
 1:05:01 File x\GRAD\addons\zeus\XEH_preClientInit.sqf, line 117
```

**Comment by AdlerSalbei** [comment]
Then I don't know why

**Comment by McDiod** [comment]
Because this didn't get released and isn't in our modset.

**Comment by McDiod** [comment]
fix worked
