### ISSUE TITLE
encrypted deployment keys don't work

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/gruppe_adler_mod#15]
I was hoping the Windows warning in 2.5 was outdated, but I got the same error message as described in the corresponding issue.

~~Please do this with your credentials on Linux @Fusselwurm :~~
https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md

**Comment by McDiod** [comment]
nevermind, works now :>

**Comment by McDiod** [comment]
Nevermind, only worked because the old deployment key was used. 

***

So far we have an SSH key pair.

GitHub has the public key as a deployment key for this repo, see here:
https://github.com/gruppe-adler/gruppe_adler_mod/settings/keys

The private key is part of the repo (tools/github_deploy_key.enc), but encrypted. Travis then decrypts it during the build with two environment variables. See here:
https://travis-ci.org/gruppe-adler/gruppe_adler_mod/settings

I then tried to use that decrypted key to deploy to our releases. See here:
https://github.com/gruppe-adler/gruppe_adler_mod/blob/e3ad4ba0e7e204f908dd542f3e50f9d78d8c733d/.travis.yml#L14

Doesn't work. Any ideas?

**Comment by Fusselwurm** [comment]
kA, das einzige das google mir sagt ist daß der key dann wohl falsch verschlüsselt wurde :/
ich hab den deploy-key mal gekillt, weil mir die ganzen fehlermeldungen etwas zu öffentlich waren ("invalid option api-key=--hier private key--" :sweat: ). ich probier's mal mit nem neuen, aber der selben anleitung, vllt hab ich nen glückstag ;)

**Comment by Fusselwurm** [comment]
ergebnis von iwie gefühlt 2h rumpusseln: deploy key != api key.

**Comment by McDiod** [comment]
Ich würde dem Typen hier einfach mal glauben, dass die ursprüngliche Methode schon sicher genug war:
https://github.com/pockethub/PocketHub/issues/770

Damit könnten wir wieder hierhin zurückgehen (ggf. neuen Key generieren):
https://github.com/gruppe-adler/gruppe_adler_mod/blob/dc27dcff72a6d96f1dcf3a04bc5de13a85998ff5/.travis.yml

**Comment by Fusselwurm** [comment]
bin dabei

**Comment by Fusselwurm** [comment]
ok, reverted in 89dd15f652967f657d8f30fffd9e9cc8802e44b6^ und neuen key in 89dd15f652967f657d8f30fffd9e9cc8802e44b6
