### ISSUE TITLE
grad_loadout only works partially for NATO-Pacific

### ISSUE THREAD

**Issue by DonkelOktor** [gruppe-adler/gruppe_adler_mod#153]
grad_loadout creates an error whilst copying the loadout to the clipboard if you use NATO-pacific as a faction. 

it creates following text
```sqf
class Type {
        class T_Soldier SL_F {
       ...
       }
}
```
instead of 
```sqf
class Type {
        class Soldier SL_F {
       ...
       }
}
```
so the sub-faction-indicator (here: T_ ) is causing the script not to work.

Do sth Salbei!

sincerely 

Not-DonkelOktor

**Comment by AdlerSalbei** [comment]
Die Beschreibung im Wiki war falsch!

**Comment by DerZade** [comment]
https://github.com/gruppe-adler/wiki.gruppe-adler.de/commit/4719ccbf216a61dfc5b685f1fd0b09f399c2a699

**Comment by Fusselwurm** [comment]
wait... also ist das jetzt ein grad-loadout-Problem? dann sollten wir dort ein ticket aufmachen

**Comment by AdlerSalbei** [comment]
@Fusselwurm Nein, wir kaluen nur deinen code :P

**Comment by McDiod** [comment]
fixed in #154
