### ISSUE TITLE
primaryWeaponUnderbarrelMagazine not copied to clipboard

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/gruppe_adler_mod#208]
1. Place a CSAT-pacific grenadier.
2. Copy its loadout to the clipboard using the grad-loadout logging feature in Eden. 
![image](https://user-images.githubusercontent.com/76476468/222924372-3f35f154-f8c3-4ea0-8c97-f9c0adb8ed1e.png)
3. Check the clipboard content in a texteditor

You will notice 2x entries with the name `primaryWeaponUnderbarrel` right after one another. 
The second entry needs to be renamed to `primaryWeaponUnderbarrelMagazine` in order to function properly.

**Comment by Fusselwurm** [comment]
(omfg the "transfer issue" feature is amazing)
