### ISSUE TITLE
move cinematicSpec to addons

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/gruppe_adler_mod#21]
- [x] test cinematicSpec in a "real" scenario ( 2+ people)
- [x] remove default keybinding (because it might conflict with other things)
- [x] fix #31
- [x] #41 ensure that leaving ACE spec also makes you leave the BIS cam :grimacing: 
- [ ] #60 move to addons

**Comment by nomisum** [comment]
@McDiod @Fusselwurm how about moving? I think we never had any issues, did we? Without actually keybinding the entry key nothing will happen anyway.

**Comment by Fusselwurm** [comment]
:grimacing: I had a PR open, and got so many "you should do it that way" comments that it would've amounted to a rewrite… at a point where I didnt have time (and too much interest, tbh) to do much about it.

**Comment by Fusselwurm** [comment]
imo we can directly move it. there's no bugs I encountered. Rewriting/making it better is still something any likely candidate is free to try their hands on. :)

**Comment by McDiod** [comment]
I haven't kept up with this. If freespec is disabled in ACE or EG spectator, does this still allow me to move the cam freely?

**Comment by Fusselwurm** [comment]
> I haven't kept up with this. If freespec is disabled in ACE or EG spectator, does this still allow me to move the cam freely?

no :)

https://github.com/gruppe-adler/gruppe_adler_mod/blob/605e54b5358b2d7edcf9c012e13817b6ddf1011a/addons/cinematicSpec/functions/fn_ui_eg_handleKeyDown.sqf#L20-L23

**Comment by McDiod** [comment]
No problem with moving it then, on my end.
