### ISSUE TITLE
Map Marker

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/gruppe_adler_mod#45]
Taktische Zeichen und Symbole ingame in der Map zu setzen ist sehr umständlich. Wenn man korrekte Zeichen und Symbole verwenden möchte, muss man teilweise sehr lange nach unten scrollen. Als Beispiel, im englischen Client mal nach "Ordnance" suchen.

Mein Vorschlag ist es, die NATO Symbole in einem Block linksseitig der Textbox anzuordnen, so dass nicht mehr gescrollt werden muss. Die taktischen Zeichen könnten dann in einem Block rechtsseitig der Textbox platziert werden. Die Farben könnten unterhalb angebracht werden.

Dieser Vorschlag ist nicht besonders dringend, würde aber für Führungselemente die QoL erheblich steigern und vielleicht andere Leute auch motivieren, etwas genauer zu werden beim Bevölkern einer taktischen Karte mit Intel-Informationen.

Vielen Dank für das Durchlesen. Issue primär geöffnet, damit die Idee nicht untergeht. :)

**Comment by nomisum** [comment]
relevant: https://www.youtube.com/watch?v=XFTxV535fk8

**Comment by Fusselwurm** [comment]
Ja, dieses Rad müssen wir vllt nicht unbedingt neu erfinden…
 BIF-Link zu Nomis Video: https://forums.bistudio.com/forums/topic/174023-sweet-markers-system/

**Comment by SlantX** [comment]
Sweet Map Marker erfüllt alle Wünsche, ich schliesse das hier mal vorläufig.
