### ISSUE TITLE
HUD Element für Combatpace

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/gruppe_adler_mod#48]

**Comment by Fusselwurm** [comment]
nice! manchmal passiert's mir daß ich das nich merke. eigentlich könnte man auch eins für latschen vs laufen dazu packen.

**Comment by SlantX** [comment]
Das wäre sehr nützlich!

**Comment by McDiod** [comment]
https://github.com/gruppe-adler/gruppe_adler_mod/tree/hud

Derzeit noch unsicher wo das Ein-/Ausblenden beim Stancewechsel ausgelöst wird.

**Comment by McDiod** [comment]
Gibt keine nicht-hackige Lösung.
