### ISSUE TITLE
Map nicht zoombar im screenshotMode

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/gruppe_adler_mod#49]
Mit aktiviertem Screenshotmode ist die Karte nicht mehr per Mausrad zoombar.

**Comment by chris579** [comment]
Kann ich nicht reproduzieren. Meinst du die ganze normale Karte, die man mit `M` öffnet?

**Comment by Fusselwurm** [comment]
ja, die ganz normale Karte. – Ich werds nochmal antesten, hab mich auch gebührend gewundert drüber, aber das Symptom war zuverlässig mit screenshot mode reproduzierbar.  :thinking:

**Comment by Fusselwurm** [comment]
möglicherweise gefixt mit https://github.com/CBATeam/CBA_A3/pull/890

**Comment by Fusselwurm** [comment]
(yip, scheint gefixt zu sein)
