### ISSUE TITLE
Join Button verschoben

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/gruppe_adler_mod#58]
Wie man auf dem Bild sieht ist der Join Button halb aus dem Bild verschoben.
Das sind die Bildschirm einstellungen:
Fullscreen window 16:10 resolution 2304x1440

[Bild](https://dedmen.de/sharex/arma3_2017-12-17_19-14-11.png)

**Comment by McDiod** [comment]
Bild bitte :)

**Comment by dedmen** [comment]
![](https://dedmen.de/sharex/arma3_2017-12-17_19-14-11.png)

**Comment by chris579** [comment]
PixelGrid durch Safezones ersetzen
