### ISSUE TITLE
Improve cinemaCam

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/gruppe_adler_mod#82]
- [ ] Entry point ACE Spec should be placed on exit point cinemaCam
- [ ] Add option (keybind) to mute other spectators – meaning exit TFAR spectator channel and mute player 

`0 call TFAR_fnc_setVoiceVolume;` // 
`player setVariable ["tf_unable_to_use_radio", true];`

**Comment by Fusselwurm** [comment]
I *think* that already worked with tfar-1.0 :thinking:

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/gruppe_adler_mod/blob/master/optionals/cinematicSpec/functions/fn_cam.sqf#L69

Should set ACE spec cam position and I think this worked once. What changed? Do we need some delay here too?

**Comment by Fusselwurm** [comment]
no idea :(

**Comment by Fusselwurm** [comment]
also see #43
